### ISSUE TITLE
tcp/udp in configuration

### ISSUE THREAD

**Issue by intelligent002** [Enigmatis/polaris-logs#65]
guys, is it possible to arrange a configuration entry that will decide either to use TCP or UDP transport ?

**Comment by intelligent002** [comment]
any feedback ?

**Comment by chenshoo** [comment]
Yes, we'll get to it in the next month or so

**Comment by leotolk** [comment]
I'm currently working on it

**Comment by intelligent002** [comment]
any updates on that one ?

**Comment by leotolk** [comment]
Its completed and working in the latest version (4.0.1). 
Look at README.md example.
